### ISSUE TITLE
[REFACTOR] 회원가입 알림 창

### ISSUE THREAD

**Issue by jinjero** [InvestMingle/IM-FE#27]
## Todo
- [x] 이메일, 닉네임 중복 확인 버튼 활성화
- [x] 회원가입(sign up) 버튼 활성화 조건 설정
- [x] 알림 창 메시지 수정
